### ISSUE TITLE
Unsupported Magisk version when trying to detach via terminal

### ISSUE THREAD

**Issue by TTVert** [Magisk-Modules-Repo/Detach#10]
I'm running latest magisk  v642788ab(277).  I don't see the typical magisk versions as I used to (17.x/18.x, etc).  I am running pie on a pixel 3a.

**Comment by takobaba** [comment]
same issue here

**Comment by xerta555** [comment]
Sorry for the delay, the new stable version fix this issue.

**Comment by TTVert** [comment]
I'm on what seems to be the latest f7142e69 and still get this.  Is that the latest or isit not available yet?
