### ISSUE TITLE
not compatible wit magisk 21000

### ISSUE THREAD

**Issue by NSP-0123456** [Magisk-Modules-Repo/Detach#13]
Once magisk have been updated to version 21.0 (21000) detach do not work anymore and print an incompatibility message.
"Unsupported Magisk version: 21000"

**Comment by Thyrador** [comment]
https://github.com/Magisk-Modules-Repo/Detach/pull/16/commits/b08ffa78681712c233ae30216599ad8dfc261a14
Please have a look and change your detach.sh accordingly.

**Note: this is just a temporary fix until it gets added to the release.**

**Comment by NSP-0123456** [comment]
This is what i did and repacked into a zip for install,.

**Comment by xerta555** [comment]
The last version with this commit The last version with this commit 9288e96 fix this issue. fix this issue.
