### ISSUE TITLE
Magisk 21001 Support

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/Detach#14]
Add Magisk 21001 support

**Comment by Thyrador** [comment]
https://github.com/Magisk-Modules-Repo/Detach/pull/16/commits/b08ffa78681712c233ae30216599ad8dfc261a14
Please have a look and change your detach.sh accordingly.

**Note: this is just a temporary fix until it gets added to the release.**

**Comment by xerta555** [comment]
The last version with this commit https://github.com/Magisk-Modules-Repo/Detach/commit/9288e9609fade2404105d2bb10bb03c9fc7aab52 fix this issue.
