### ISSUE TITLE
store files somewhere other than root

### ISSUE THREAD

**Issue by bengalih** [Magisk-Modules-Repo/Detach#15]
would be nice if the files didn't need to live in root of sd card.
module creates several files with names that are not descriptive and may conflict with other apps/modules.

**Comment by xerta555** [comment]
I did this choice for the simplicity.

But if you have better idea(s), i listen you :)

**Comment by bengalih** [comment]
https://topjohnwu.github.io/Magisk/guides.html#:~:text=A%20Magisk%20module%20is%20a,adb%2Fmodules%20%E2%94%9C%E2%94%80%E2%94%80%20.

/data/adb/modules/detach 

would be the recommended location according to the guidelines.

**Comment by xerta555** [comment]
Effectivly it's recommanded to store any files of a Magisk module in the module folder itself.

But as in our case it's the setup file for the module (wich must exist in the internal storage before first module install), i did a vote on the Telegram group (link in the README of the module), and the result of the vote was the internal storage.

**Comment by bengalih** [comment]
Then I would recommend a /detach folder in root of card or at least prefixing file names with "dt-" "detach-" or similar.  Current configuration is poor form: unidentifiable, may conflict with others, etc.

thanks for consideration.

**Comment by xerta555** [comment]
> Then I would recommend a /detach folder in root of card or at least prefixing file names with "dt-" "detach-" or similar. Current configuration is poor form: unidentifiable, may conflict with others, etc.

The evoked reason is quite acceptable, only the file is already named "Detach.txt", i had made a poll on this subject on the Telegram group that i had left active for a long enough time.

The result of the poll was unequivocal: more than 90% of the users of the module as well as the newcomers wanted a simple file named "Detach.txt" present at the root of the internal storage space of the device, in other words: `/sdcard/Detach.txt` (or equivalent: `/storage/emulated/0/Detach.txt`).
