### ISSUE TITLE
Doesn't sustain reboot. Don't work perfectly. Does not last long enough.

### ISSUE THREAD

**Issue by PranavBhattarai** [Magisk-Modules-Repo/Detach#2]
There should be a way to provide u look logs from terminal. 
This is a trending feature seen in modules these days.

**Comment by xerta555** [comment]
> There should be a way to provide u look logs from terminal.

Indeed, I don't program automatic error export in my scripts, at least not yet.
Do you have any suggestions on the different ways of doing this?

**Comment by PranavBhattarai** [comment]
Can't u learn from opensource module available in this platform? "Pix3lify" is one of the module which provides this feature. (P.S: I don't know who to do this? Barely a programmer. So, no.)

**Comment by xerta555** [comment]
All infos in https://github.com/Magisk-Modules-Repo/Detach/issues/4
