### ISSUE TITLE
Detach.txt error after flash or execute "detach -id"

### ISSUE THREAD

**Issue by JeelsBoobz** [Magisk-Modules-Repo/Detach#20]
Hello sir, i found many issue like Detach.txt error [on screenshot] and other application can't detach using `detach -id`
![Screenshot_20201102-154850](https://user-images.githubusercontent.com/38210868/97848327-80fc2080-1d23-11eb-8b36-4681ee395370.jpg)

**Comment by xerta555** [comment]
Wrong Detach.txt syntax.
Take the original file and edit again only what u need.
