### ISSUE TITLE
Module appears to be generally broken... 

### ISSUE THREAD

**Issue by flatline-studios** [Magisk-Modules-Repo/Detach#21]
Running:

`su -c detach -id com.google.android.youtube`

Outputs:

```
Compatibility check... ✓

Detach v4.2

Detach work in progress...

Done

$
```

Then running:

`su -c detach -l`

Outputs:

```
Compatibility check... ✓


Hidden app(s):
---------------

-

---------------

$
```

I've tried multiple methods, and nothing seems to work.

If I try to use:

`su -c detach -a`

Then get the following output :

```
Compatibility check... ✓


Please write the application package name
you want to detach from automatic PS update

Package name:
YouTube


 'YouTube' - Do you confirm ?
yes

Check if YouTube exist on the Play Store...
wget: server returned error: HTTP/1.1 404 Not Found
wget: server returned error: HTTP/1.1 404 Not Found
grep: /data/adb/modules/Detach/YouTube.html: No such file or directory
sed: bad pattern '32,-1!d;'@5 (1)
sed: Unknown option 1,42!d; (see "sed --help")

- Enable  in your /sdcard/Detach.txt file.


Done

$
```

Any ideas?

**Comment by doclucas** [comment]
Same problem here

**Comment by Pharaoh2k** [comment]
Same problem here on galaxy note 10 plus N975F with Android 11.

**Comment by takobaba** [comment]
I am on Pixel Experience A11 for Dipper(Mi8) having the same issue.  Below fixed my problem now youtube is hidden from google play.


I have downloaded the Detach.txt file to /sdcard/ location using wget:


`cd /sdcard/`
`wget https://raw.githubusercontent.com/xerta555/Detach-Files/master/Detach.txt`

Then edit the file, uncomment YouTube from the detach file:

`
vi /sdcard/Detach.txt
`

After that go to magisk manager, re-flash the detach package. Using install from storage and choose the Detach-4.2(42).zip and flash again. Reboot.

go to terminal run your commands again:


`su -c detach -id`

`su -c detach -l`


It worked for me. Hope it solves your problem.

**Comment by flatline-studios** [comment]
@takobaba

That worked, at least partially.

Downloading the text file which had permissions 0660, as opposed to 0770 that my original had. Making the edit again, and reinstalling the detach module worked after the reboot.

But, it has now stopped working, as has the detach module in general. From the command line I get:

```
1|:/ $ su
1|:/ # detach -l
/system/bin/detach[910]: -c: inaccessible or not found
Unsupported Magisk version:
1|:/ #
```

And the same happens for any detach command I run.

I don't have time to look through the detach code, but I should note the following:

```
1|:/ # magisk -c
22.0:MAGISK (22000)
```

Oh, and YouTube is back now. No restarts made... It's just been doing nothing overnight, and then this morning YouTube is back, taunting me.

Best guess, magisk 22 moved the directories that are checked for at the start of the detach binary, and now it thinks its not installed.

**Comment by Bradford1040** [comment]
Playstore updated last night! Install it again, it seems after playstore updates a reflash is needed,

Personally I am still using detach3.01.zip, on a oneplus 7tpro 5g McLaren with LOS 17.1.

**Comment by sobuj53** [comment]
Try updated version of detach and for built in scheduling use `su -c detach -t` select `crond` method.

**Comment by xerta555** [comment]
Update to the new version and feedback, thanks.
