### ISSUE TITLE
Feature request better command line interface

### ISSUE THREAD

**Issue by undermark5** [Magisk-Modules-Repo/Detach#32]
It would be awesome to implement menu functionality as seen in the systemizer module, where installed applications are displayed and you can add them by entering their number rather than having to search for the package name. This would make the command line way easier to use.

**Comment by xerta555** [comment]
> It would be awesome to implement menu functionality as seen in the systemizer module, where installed applications are displayed and you can add them by entering their number rather than having to search for the package name. This would make the command line way easier to use.

I had thought about it at the time of conception, but it is purely impossible because the developers of the Play Store do whatever they want and the logic they integrate in the application is just a nonsense.
Just one example: when you decide to set your updates to "Do not update", well you know what?
The Play Store application still updates them after a while.

**Comment by undermark5** [comment]
>  it is purely impossible because the developers of the Play Store do whatever they want and the logic they integrate in the application is just a nonsense.

I disagree with this, the functionality that I suggested is 100% possible to do (I even provided an example of a module that provides such a CLI). If you are instead trying to indicate that this module is ineffective at blocking play store automatic updates, that is a completely different issue and I believe that, however to blatantly lie about the physical possibility of being able to provide the CLI I suggested is improper. If the module is ineffective or dead, give that as the reason for not implementing the suggested CLI, not that the CLI is impossible to implement (which is how I'm understanding what you are saying).

**Comment by xerta555** [comment]
> I disagree with this, the functionality that I suggested is 100% possible to do (I even provided an example of a module that provides such a CLI). If you are instead trying to indicate that this module is ineffective at blocking play store automatic updates, that is a completely different issue and I believe that, however to blatantly lie about the physical possibility of being able to provide the CLI I suggested is improper. If the module is ineffective or dead, give that as the reason for not implementing the suggested CLI, not that the CLI is impossible to implement (which is how I'm understanding what you are saying).


I was not aware of a code to stop/cancel this, or maybe i don't remember.
