### ISSUE TITLE
Can't detach apps

### ISSUE THREAD

**Issue by PRinceBhai** [Magisk-Modules-Repo/Detach#9]
Hi, i've been using this moduke of yours for the quite some time but on now my other device which Xiaomi Redmi Note 3 (Kenzo) running AeX 6.7 Pie, i can no longer detach apps with this module. I basically need to detach two apps Which are Youtube (vanced magsk module) and Instagram.
This is how my detach.txt looks
![Detach.txt](https://i.imgur.com/vtogUuk.jpg)

And this is happens when i try "su - c detach - a" in termux
![Termux](https://i.imgur.com/npNhUlw.jpg)

Please help me find what am i doing wrong?

**Comment by zx900930** [comment]
Same problem here with twitch app
pakage name: tv.twitch.android.app
screenhot:
![logs](https://i.imgur.com/SZVJete.png)

**Comment by PRinceBhai** [comment]
@zx900930 So are you also running a Custom pie or Q Rom?

**Comment by zx900930** [comment]
@PRinceBhai 
Android 8.1.0
Custom ROM: Resurrection Remix OS v6.1.0

it's finally worked.
in detach.txt the line 45 should be:
`# Other applications`
not 
`# Other Applications`

and there is an espace behind Youtube

**Comment by PRinceBhai** [comment]
@zx900930 Okay i thought that the Hashtag makes those lines read as comments or get ignored, but i'll see also what do you mean by "There's a escape BEHIND Youtube"? I didn't quite get that.

**Comment by xerta555** [comment]
Hi

Sorry for the delay, for the last screenshoot here, it appear that you have the curl Magisk module wich is taked in consideration by Android over wget classic applet.
As this module isn't compatible with curl, thanks to disable curl module completly to be sure that you don't have any curl applet/binary file on your device. By this way, wget applet from osm0sis (from Busybox Magisk module) will be take in consideration and the module will works fine.

For the first problem here, it should works fine now with the last version uploaded a few minutes ago, so just test and feedback, don't hesitate to read more and ask on Telegram group or here if you have any question(s).
